### ISSUE TITLE
Web crash: The target <seqName> could not be identified in the dom

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#1347]
While using v3 (master.clades.nextstrain.org) I suddenly got the following error:
```
Error message: Error: The target 'stop-codons-label___index_1849__seqName_hCoV-19-USA-CA-HLX-STM-HVGZFYFHC-2023-EPI_ISL_18636933-2023-11-14' could not be identified in the dom, tip: check spelling
Nextclade version 3.0.0-alpha.0 (commit: 4fd03ba, branch: master)
Memory available: 3586 MBytes
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Browser details: {"browser":{"name":"Chrome","version":"120.0.0.0"},"os":{"name":"macOS","version":"10.15.7","versionName":"Catalina"},"platform":{"type":"desktop","vendor":"Apple"},"engine":{"name":"Blink"}}
Call stack:
Error: The target 'stop-codons-label___index_1849__seqName_hCoV-19-USA-CA-HLX-STM-HVGZFYFHC-2023-EPI_ISL_18636933-2023-11-14' could not be identified in the dom, tip: check spelling
    at https://master.clades.nextstrain.org/_next/static/chunks/pages/_app-6aab827211ced93a.js:2:618106
    at A (https://master.clades.nextstrain.org/_next/static/chunks/pages/_app-6aab827211ced93a.js:2:618212)
    at a.updateTarget (https://master.clades.nextstrain.org/_next/static/chunks/pages/_app-6aab827211ced93a.js:4:273134)
    at a.render (https://master.clades.nextstrain.org/_next/static/chunks/pages/_app-6aab827211ced93a.js:4:273496)
    at gE (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:85420)
    at gD (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:85218)
    at _ (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:120733)
    at h5 (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:107754)
    at h3 (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:107682)
    at h2 (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:107535)
```

This happened while I was filtering for clade 23B.

It may or may not be reproducible with the GISAID sequence `hCoV-19-USA-CA-HLX-STM-HVGZFYFHC-2023-EPI_ISL_18636933-2023-11-14`.

This is the first time I've hit this error as far as I can remember, and I use v3 a lot so this is not an urgent issue.

**Comment by ivan-aksamentov** [comment]
Likely jerking mouse cursor when main thread is blocked (e.g. when the algo is running, or when table is scrolled), so that anchor element for the tooltip doesn't have enough time to appear.

We need to reimplement tooltips and make them work without relying on element ids.
