### ISSUE TITLE
In web GUI when clicking on tree, getting "Type Error: undefined is not an iterable"

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#1547]
Not sure how to reproduce, but seems worth looking into:

```
Error message: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

Nextclade version 3.10.0 (commit: 59e757f, branch: master)

Memory available: 3586 MBytes

User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

Browser details: {"browser":{"name":"Chrome","version":"130.0.0.0"},"os":{"name":"macOS","version":"10.15.7","versionName":"Catalina"},"platform":{"type":"desktop","vendor":"Apple"},"engine":{"name":"Blink"}}

Call stack:

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at b._setSelectedNodes (https://master.clades.nextstrain.org/_next/static/chunks/412.20e66927d3aaae82.js:1:132108)
    at b.render (https://master.clades.nextstrain.org/_next/static/chunks/412.20e66927d3aaae82.js:1:128897)
    at d.value (https://master.clades.nextstrain.org/_next/static/chunks/412.20e66927d3aaae82.js:1:173407)
    at d.value (https://master.clades.nextstrain.org/_next/static/chunks/412.20e66927d3aaae82.js:1:174951)
    at hg (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:99176)
    at hf (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:98946)
    at hf (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:98841)
    at hf (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:98841)
    at h8 (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:111693)
    at h7 (https://master.clades.nextstrain.org/_next/static/chunks/framework-5774a691a4029c28.js:1:108246)
```

I ran Nextclade like this:
https://master.clades.nextstrain.org/?dataset-name=nextstrain/sars-cov-2/BA.2.86&input-tree=https://nextstrain.org/charon/getDataset?prefix=staging/nextclade/sars-cov-2/BA.2.86

With data from GISAID shared via Slack

What's strange is that this error only happened after roughly the following sequence:
1. Run Nextclade
2. Navigate to tree
3. Do some filtering/coloring on tree
4. Navigating back to Nextclade results table
5. Applying an AA filter like ORF1a:1639 to the results table
6. Then clicking again on tree, this is when Nextclade crashed

**Comment by corneliusroemer** [comment]
This is the tree JSON 
[staging_nextclade_sars-cov-2_BA.2.86.json](https://github.com/user-attachments/files/17719184/staging_nextclade_sars-cov-2_BA.2.86.json)

**Comment by corneliusroemer** [comment]
I think this is an upstream bug, as I've encountered it outside of Auspice as well.

We could potentially handle Auspice bugs like this better and not crash all of Nextclade, just say "Auspice crashed" and still allow the user to navigate back to the results table.

**Comment by corneliusroemer** [comment]
Should we revert https://github.com/nextstrain/nextclade/pull/1546 until upstream fixes this? @ivan-aksamentov

**Comment by corneliusroemer** [comment]
Great thanks! What do you think about not crashing on Auspice errors? Probably not really that important as Auspice crashes rarely but if it's easy to do :)
