### ISSUE TITLE
Error message: Error: When reading a fasta record: Expected character '>' at record start.

### ISSUE THREAD

**Issue by basmaelsaadani** [nextstrain/nextclade#1560]
Error message: Error: When reading a fasta record: Expected character '>' at record start.

Nextclade version 3.10.0 (commit: 6489d24, branch: release)

Memory available: 2222 MBytes

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

Browser details: {"browser":{"name":"Chrome","version":"131.0.0.0"},"os":{"name":"Windows","version":"NT 10.0","versionName":"10"},"platform":{"type":"desktop"},"engine":{"name":"Blink"}}

Call stack:

Error: When reading a fasta record: Expected character '>' at record start.
    at A (https://clades.nextstrain.org/_next/static/chunks/68.6fe6624798e33815.js:1:9418)
    at https://clades.nextstrain.org/_next/static/wasm/136357611caedf0d.wasm:wasm-function[3056]:0x302a9f
    at Function.value (https://clades.nextstrain.org/_next/static/chunks/68.6fe6624798e33815.js:1:6470)
    at https://clades.nextstrain.org/_next/static/chunks/68.6fe6624798e33815.js:1:18799
    at u (https://clades.nextstrain.org/_next/static/chunks/444.170c49d0571b2ba1.js:1:28086)
    at Generator._invoke (https://clades.nextstrain.org/_next/static/chunks/444.170c49d0571b2ba1.js:1:29376)
    at a.<computed> [as next] (https://clades.nextstrain.org/_next/static/chunks/444.170c49d0571b2ba1.js:1:28489)
    at p (https://clades.nextstrain.org/_next/static/chunks/68.6fe6624798e33815.js:1:14701)
    at d (https://clades.nextstrain.org/_next/static/chunks/68.6fe6624798e33815.js:1:14898)
    at https://clades.nextstrain.org/_next/static/chunks/68.6fe6624798e33815.js:1:14957

**Comment by corneliusroemer** [comment]
Maybe for web, we can catch this error and check if the text is a single valid sequence (ACGT etc) just without fasta header and if that's the case add a simple name like "sequence".

I think this is the most common error people get using web Nextclade, they paste a single sequence without header
