### ISSUE TITLE
worker.js not found?

### ISSUE THREAD

**Issue by biocyberman** [nextstrain/nextclade#269]
Nextclade is asking for a non-existent module. I tried on both release and alpha version:

```
npm install --global @neherlab/nextclade@alpha
/mc3/envs/nextclade/bin/nextclade -> /mc3/envs/nextclade/lib/node_modules/@neherlab/nextclade/dist/nextclade.js
/mc3/envs/nextclade/bin/nextclade.js -> /mc3/envs/nextclade/lib/node_modules/@neherlab/nextclade/dist/nextclade.js
+ @neherlab/nextclade@0.8.0-alpha.7
updated 1 package in 3.624s
$ nextclade -i sequences.fasta -t tmp_nextclade.tsv --jobs 20
Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/mc3/envs/nextclade/lib/node_modules/@neherlab/nextclade/dist/worker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout.setTimeout [as _onTimeout] (/mc3/envs/nextclade/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:934:2216)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
~$ ls -lah /mc3/envs/nextclade/lib/node_modules/@neherlab/nextclade/dist/worker.js
ls: cannot access '/mc3/envs/nextclade/lib/node_modules/@neherlab/nextclade/dist/worker.js': No such file or directory
```

**Comment by ivan-aksamentov** [comment]
Hi @biocyberman, sorry you are experiencing this.


What is you Node.js version?
```
node --version
```
For Nextclade to run properly, we require Node.js version >= 12, and recommend the current LTS series >= 14.15.0. See [README.md#quick-start](https://github.com/nextstrain/nextclade/blob/master/README.md#quick-start).

Also, we are not encouraging using alpha versions. Please try the latest release:

```
npm install --global @neherlab/nextclade@latest
nextclade --version
```
(should be `0.8.0-1` as of right now)


If nothing works, maybe you could try a containerized version? It includes everything needed, including the  recommended version of Node.js. You only need [Docker to be installed](https://docs.docker.com/get-docker/) on your machine. See [README.md#with-docker](https://github.com/nextstrain/nextclade/blob/master/packages/cli/README.md#with-docker).

**Comment by ivan-aksamentov** [comment]
@biocyberman Let me know if you was able to resolve this issue or if you need more help.

**Comment by biocyberman** [comment]
Hi @ivan-aksamentov I could run with docker image, but still fail on if I install with `npm`. I haven't tried with `yarn`. Probably it does a better job.

**Comment by ivan-aksamentov** [comment]
@biocyberman have you tried the latest stable version [0.8.1](https://www.npmjs.com/package/@neherlab/nextclade?activeTab=versions)?

You could also try to run with [`npx`](https://stackoverflow.com/questions/50605219/difference-between-npx-and-npm), without installation:

```bash
npx @neherlab/nextclade
```

or

```
npx @neherlab/nextclade@0.8.1
```
to install a concrete version.

**Comment by biocyberman** [comment]
Still the same problem:

```
 npx @neherlab/nextclade -i test6040.fasta -t test.tsv -j 8
Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/opt/mc3/envs/nextclade/lib/node_modules/@neherlab/nextclade/dist/worker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
~$ npx @neherlab/nextclade -i test6040.fasta -o test.json  -j 8
Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module /opt/mc3/envs/nextclade/lib/node_modules/@neherlab/nextclade/dist/worker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

```

But I figured it out: I used conda and it install the outdated nodejs version. This helped:

```
$ conda env remove --name nextclade
$ conda create --name nextclade -c conda-forge nodejs
$ npm install --global @neherlab/nextclade
```

**Comment by ivan-aksamentov** [comment]
@biocyberman Great! Glad it worked. We indeed only support recent Node versions, because we are using advanced features not available in the old ones.

I'm closing this issue then. But feel free to reopen or to submit another issue if you still have questions/problems.
