### ISSUE TITLE
BUG: Cannot read properties of undefined (reading 'filter') when typing in filtering field

### ISSUE THREAD

**Issue by fyl1600** [nextstrain/nextclade#968]
TypeError: Cannot read properties of undefined (reading 'filter')
    at br (https://clades.nextstrain.org/_next/static/chunks/pages/_app-57aecb6ed37fb90f.js:3:958393)
    at https://clades.nextstrain.org/_next/static/chunks/pages/_app-57aecb6ed37fb90f.js:3:961138
    at u (https://clades.nextstrain.org/_next/static/chunks/main-9c3c3e678ac23665.js:1:1333)
    at Generator._invoke (https://clades.nextstrain.org/_next/static/chunks/main-9c3c3e678ac23665.js:1:2623)
    at Generator.a.<computed> [as next] (https://clades.nextstrain.org/_next/static/chunks/main-9c3c3e678ac23665.js:1:1736)
    at bv (https://clades.nextstrain.org/_next/static/chunks/pages/_app-57aecb6ed37fb90f.js:3:959830)
    at d (https://clades.nextstrain.org/_next/static/chunks/pages/_app-57aecb6ed37fb90f.js:3:960028)

**Comment by ivan-aksamentov** [comment]
@fyl1600 There's been a problem with website's infrastructure. This should be resolved now. Please try again and let us know if it works for you.

If problem persists, please provide some more details, where possible: 
 - data that you are using
 - exact steps to reproduce the error
 - screenshots or screencast of the process

In order to investigate and fix the problem developers need to reproduce it on their machines.

**Comment by corneliusroemer** [comment]
Thanks for the report @fyl1600! In general it's very useful to know which platform you're using, browser, website you type in, when the error occurs (after loading or after clicking some button, etc.).
